# Generated by Django 4.0.4 on 2022-05-03 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='teg',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_storage.tegbook'),
        ),
    ]
