# Generated by Django 4.0.4 on 2022-05-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_storage', '0002_book_teg'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='FileBook',
        ),
        migrations.AlterModelTable(
            name='tegbook',
            table='TegBook',
        ),
    ]
